-- MySQL Script generated by MySQL Workbench
-- Mon Dec  2 11:16:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
  @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @ @SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema magasin
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema magasin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `magasin` DEFAULT CHARACTER SET utf8;

USE `magasin`;

-- -----------------------------------------------------
-- Table `magasin`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `client_nom` VARCHAR(255) NOT NULL,
  `client_prenom` VARCHAR(255) NOT NULL,
  `client_mot_de_passe` VARCHAR(255) NOT NULL,
  `client_courriel` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_courriel_UNIQUE` (`client_courriel` ASC)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `magasin`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`commandes` (
  `commande_id` INT NOT NULL AUTO_INCREMENT,
  `commande_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `commande_client_id` INT NOT NULL,
  PRIMARY KEY (`commande_id`),
  INDEX `fk_commandes_clients_idx` (`commande_client_id` ASC),
  CONSTRAINT `fk_commandes_clients` FOREIGN KEY (`commande_client_id`) REFERENCES `magasin`.`clients` (`client_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `magasin`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`categories` (
  `categorie_id` INT NOT NULL AUTO_INCREMENT,
  `categorie_nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`categorie_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `magasin`.`marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`marques` (
  `marque_id` INT NOT NULL AUTO_INCREMENT,
  `marque_nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`marque_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `magasin`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`produits` (
  `produit_id` INT NOT NULL AUTO_INCREMENT,
  `produit_nom` VARCHAR(255) NOT NULL,
  `produit_description` VARCHAR(255) NOT NULL,
  `produit_prix` DECIMAL(8, 2) NOT NULL,
  `produit_quantite` INT NOT NULL DEFAULT 0,
  `produit_categorie_id` INT NOT NULL,
  `produit_marque_id` INT NOT NULL,
  PRIMARY KEY (`produit_id`),
  INDEX `fk_produits_categories1_idx` (`produit_categorie_id` ASC),
  INDEX `fk_produits_marques1_idx` (`produit_marque_id` ASC),
  CONSTRAINT `fk_produits_categories1` FOREIGN KEY (`produit_categorie_id`) REFERENCES `magasin`.`categories` (`categorie_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_marques1` FOREIGN KEY (`produit_marque_id`) REFERENCES `magasin`.`marques` (`marque_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `magasin`.`produits_commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magasin`.`produits_commandes` (
  `produits_produit_id` INT NOT NULL,
  `commandes_commande_id` INT NOT NULL,
  `produit_commande_quantite` INT NOT NULL,
  PRIMARY KEY (`produits_produit_id`, `commandes_commande_id`),
  INDEX `fk_produits_has_commandes_commandes1_idx` (`commandes_commande_id` ASC),
  INDEX `fk_produits_has_commandes_produits1_idx` (`produits_produit_id` ASC),
  CONSTRAINT `fk_produits_has_commandes_produits1` FOREIGN KEY (`produits_produit_id`) REFERENCES `magasin`.`produits` (`produit_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_produits_has_commandes_commandes1` FOREIGN KEY (`commandes_commande_id`) REFERENCES `magasin`.`commandes` (`commande_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

INSERT INTO
  marques(marque_nom)
VALUES
  ("Adidas"),
  ("Nike"),
  ("Lacoste");

INSERT INTO
  categories(categorie_nom)
VALUES
  ("Golf"),
  ("Marche"),
  ("Natation");

INSERT INTO
  clients (
    client_nom,
    client_prenom,
    client_courriel,
    client_mot_de_passe
  )
VALUES
  (
    "admin",
    "admin",
    "admin@magasin.com",
    SHA2('admin', 256)
  ),
  (
    "Bricoleur",
    "Bob",
    "bob@bricoleur.com",
    SHA2('bob', 256)
  ),
  (
    "Boncoup",
    "Sandra",
    "sandra@boncoup.com",
    SHA2('Sandra', 256)
  ),
  (
    "Sacoche",
    "Samuel",
    "samuel@sacoche.com",
    SHA2('Samuel', 256)
  ),
  (
    "Jeremy",
    "Ron",
    "ron@jeremy.com",
    SHA2('Ron', 256)
  ),
  (
    "Michepoil",
    "Sarah",
    "sarah@michepoil.com",
    SHA2('Sarah', 256)
  ),
  (
    "Touille",
    "Sacha",
    "sacha@touille.com",
    SHA2('Sacha', 256)
  ),
  (
    "Flovia",
    "Milla",
    "milla@flovia.com",
    SHA2('Milla', 256)
  ),
  (
    "Ramsay",
    "Gordon",
    "ramsay@gordon.com",
    SHA2('Gordon', 256)
  ),
  (
    "Toiletrou ",
    "Ginette",
    "ginette@toiletrou.com",
    SHA2('Ginette', 256)
  );

INSERT INTO
  produits (
    produit_nom,
    produit_description,
    produit_prix,
    produit_categorie_id,
    produit_marque_id,
    produit_quantite
  )
VALUES
  (
    "Chandail de marche",
    "Chandail pour la marche sportive intense.",
    59.99,
    2,
    1,
    55
  ),
  (
    "Montre intelligente",
    "Permets de calculer vos pas.",
    159.99,
    2,
    2,
    23
  ),
  (
    "Chaussures",
    "Évite d'avoir mal au genou",
    79.99,
    2,
    3,
    38
  ),
  (
    "Casque de bain",
    "Casque qui se porte sur le tête",
    19.99,
    3,
    2,
    79
  ),
  (
    "Lunette aquatique",
    "Évite d'avoir les yeux mouillés",
    9.99,
    3,
    1,
    42
  ),
  (
    "Kit de plongée",
    "Gagné en vitesse et confort aquatique",
    89.99,
    3,
    3,
    5
  ),
  (
    "Chaussures de golf",
    "Chaussures qui permettent de faire un trou d'un coup sans avoir mal aux pieds",
    259.99,
    1,
    3,
    69
  ),
  (
    "Gant de golf",
    "Gant légendaire doit être préférablement porté avec les chaussures de golf",
    39.99,
    1,
    3,
    156
  ),
  (
    "Polo de golf",
    "Polo légendaire",
    59.99,
    1,
    3,
    60
  );

INSERT INTO
  commandes (commande_client_id, commande_date)
VALUES
  (1, "2019-10-11"),
  (2, "2019-12-11"),
  (3, "2019-02-03"),
  (4, "2019-11-22"),
  (5, "2019-08-25"),
  (6, "2019-11-15"),
  (7, "2019-03-04"),
  (8, "2019-06-25"),
  (9, "2019-05-30"),
  (1, "2019-10-11"),
  (2, "2019-09-11"),
  (3, "2019-11-12"),
  (4, "2019-09-12"),
  (5, "2019-11-12"),
  (6, "2019-01-13"),
  (7, "2019-12-13"),
  (8, "2019-11-13"),
  (9, "2019-10-14"),
  (1, "2019-05-15"),
  (2, "2019-11-16"),
  (3, "2019-12-16"),
  (4, "2019-04-16");

INSERT INTO
  produits_commandes (
    produits_produit_id,
    commandes_commande_id,
    produit_commande_quantite
  )
VALUES
  (2, 1, 10),
  (3, 2, 5),
  (4, 3, 6),
  (5, 4, 8),
  (6, 5, 7),
  (7, 6, 4),
  (8, 7, 3),
  (9, 8, 2),
  (3, 9, 9),
  (4, 10, 4),
  (7, 11, 3),
  (2, 12, 10),
  (3, 13, 5),
  (4, 14, 6),
  (5, 15, 8),
  (6, 16, 7),
  (7, 17, 4),
  (8, 18, 3),
  (9, 19, 2),
  (3, 20, 9),
  (4, 21, 4),
  (7, 22, 3);
  