-- MySQL Script generated by MySQL Workbench
-- Wed Jan 22 14:30:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lunadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lunadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lunadb` DEFAULT CHARACTER SET utf8 ;
USE `lunadb` ;

-- -----------------------------------------------------
-- Table `lunadb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`clients` (
  `clients_id` INT NOT NULL,
  `clients_adresse` VARCHAR(45) NOT NULL,
  `clients_telephone` VARCHAR(45) NOT NULL,
  `clients_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`clients_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunadb`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`commandes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `commandes_adresse` VARCHAR(45) NOT NULL,
  `commandes_etat` VARCHAR(45) NOT NULL,
  `commandes_commentaire` VARCHAR(45) NULL,
  `fk_client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_client1_idx` (`fk_client_id` ASC),
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`fk_client_id`)
    REFERENCES `lunadb`.`clients` (`clients_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunadb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `categories_nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunadb`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`produits` (
  `produits_id` INT NOT NULL AUTO_INCREMENT,
  `produits_nom` VARCHAR(45) NOT NULL,
  `produits_description` VARCHAR(255) NOT NULL,
  `produits_prix` DECIMAL NOT NULL,
  `produits_quantite` INT NOT NULL,
  `fk_categorie_id` INT NOT NULL,
  PRIMARY KEY (`produits_id`),
  INDEX `fk_produit_categorie1_idx` (`fk_categorie_id` ASC),
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`fk_categorie_id`)
    REFERENCES `lunadb`.`categories` (`categories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunadb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`utilisateurs` (
  `utilisateurs_nom` VARCHAR(45) NOT NULL,
  `utilisateurs_password` VARCHAR(45) NOT NULL,
  `utilisateurs_privilege` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`utilisateurs_nom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lunadb`.`commandes_produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lunadb`.`commandes_produits` (
  `quantite_produit` INT NOT NULL,
  `commande_id` INT NOT NULL,
  `produit_id` INT NOT NULL,
  PRIMARY KEY (`commande_id`, `produit_id`),
  INDEX `fk_commande_produit_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_commande_produit_commande`
    FOREIGN KEY (`commande_id`)
    REFERENCES `lunadb`.`commandes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_produit_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `lunadb`.`produits` (`produits_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
